export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGIN_FAILURE = "REQUEST_LOGIN_FAILURE";
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS";
export const REQUEST_LOGIN_TIMEOUT = "REQUEST_LOGIN_TIMEOUT";
